#!/usr/bin/env bash
# install and configures HAproxy on the server
# to load balance between two servers

sudo apt-get -y update
sudo apt -y install haproxy
echo "
frontend node-http
    bind *:80
    mode http
    default_backend the_backend
backend the_backend
    balance roundrobin
    option forwardfor
    server 22691-web-01 3.239.87.85:80 check
    server 22691-web-02 44.200.87.28:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
service haproxy restart
